esphome:
  name: ld2450-radar
  friendly_name: LD2450 Radar

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "wi-fi_home_tech"
  password: "13579kuzn"

api:
  encryption:
    key: "wYW+mT/9xrhAwiqiHsZR7HLvXOSycF/Z0dgYkLUdxCY="

logger:
  baud_rate: 115200

ota:
  - platform: esphome
    password: "6d2ff09e0caa972526b4446d82043c04"
