esphome:
  name: ld2450-radar
  friendly_name: LD2450 Radar

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: "wi-fi_home_tech"
  password: "13579kuzn"

api:
  encryption:
    key: "wYW+mT/9xrhAwiqiHsZR7HLvXOSycF/Z0dgYkLUdxCY="

logger:
  baud_rate: 115200

ota:
  - platform: esphome
    password: "6d2ff09e0caa972526b4446d82043c04"

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000

sensor:
  - platform: ld2450
    mac_address:
      name: "LD2450 MAC"
    
    target_1:
      x:
        name: "Target 1 X"
        id: target1_x
      y:
        name: "Target 1 Y" 
        id: target1_y
