substitutions:
  devicename: ld2450-test

esphome:
  name: ${devicename}

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "wi-fi_home_tech"
  password: "13579kuzn"

api:
  encryption:
    key: "wYW+mT/9xrhAwiqiHsZR7HLvXOSycF/Z0dgYkLUdxCY="

logger:
  level: DEBUG
  baud_rate: 115200

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
