esphome:
  name: ld2450-radar

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "wi-fi_home_tech"
  password: "13579kuzn"

api:

logger:
  baud_rate: 115200

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
