name: ESPHome Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build ESPHome firmware
      uses: esphome/compile-skill@v2
      with:
        yaml_file: lidar.yaml  # ваш yaml файл
        esphome_version: "2025.9.3"
        
    - name: List build files
      run: |
        echo "=== Listing build directory ==="
        find . -name "*.bin" -type f | head -20
        echo "=== ESPHome build structure ==="
        find .esphome -type f -name "*.bin" 2>/dev/null || echo "No bin files found in .esphome"
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lidar-firmware
        path: |
          .esphome/build/lidar/.pioenvs/lidar/firmware.bin
          .esphome/build/lidar/.pioenvs/lidar/firmware.factory.bin
          .esphome/build/lidar/.pioenvs/lidar/firmware.ota.bin
        if-no-files-found: error
