name: ESPHome Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with ESPHome
      run: |
        pip install esphome
        esphome compile lidar.yaml
        
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/lidar/.pioenvs/lidar/firmware.bin
          build/lidar/.pioenvs/lidar/firmware.factory.bin
          build/lidar/.pioenvs/lidar/firmware.ota.bin
