name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile with Docker
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
        
    - name: Find and list all firmware files
      run: |
        echo "=== Searching for firmware files ==="
        find . -name "*.bin" -type f | grep -v ".git" | head -20 || echo "No bin files found"
        echo "=== Build directory structure ==="
        find .esphome -type f -name "*.bin" 2>/dev/null | head -10 || echo "No files in .esphome"
        
    - name: Upload ANY found firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-files
        path: |
          .esphome/build/**/*.bin
        if-no-files-found: warn
