name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile and prepare firmware
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
        # Копируем все bin файлы в корень для простоты
        cp .esphome/build/ld2450-radar/.pioenvs/ld2450-radar/*.bin . || echo "Copy failed but continuing"
        
    - name: Upload firmware from root
      uses: actions/upload-artifact@v4
      with:
        name: ld2450-firmware
        path: "*.bin"
