name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile and find firmware
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
        # Копируем все .bin файлы в корень
        find . -name "*.bin" -exec cp {} . \;
        
    - name: Upload all bin files
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: "*.bin"
