name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile with Docker
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
        
    - name: Find and upload firmware
      run: |
        find . -name "firmware.factory.bin" -exec cp {} . \;
        find . -name "firmware.ota.bin" -exec cp {} . \;
        
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: "firmware*.bin"
