name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile with Docker
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
        
    - name: Copy firmware files
      run: |
        # Копируем файлы прошивки в корень
        cp /config/.esphome/build/ld2450/.pioenvs/ld2450/firmware.ota.bin ld2450-ota.bin
        cp /config/.esphome/build/ld2450/.pioenvs/ld2450/firmware.factory.bin ld2450-factory.bin
        cp /config/.esphome/build/ld2450/.pioenvs/ld2450/firmware.bin ld2450.bin
        ls -la *.bin
        
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: ld2450-firmware
        path: |
          ld2450-ota.bin
          ld2450-factory.bin
          ld2450.bin
