name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile and show full output
      run: |
        # Запускаем компиляцию и сохраняем полный вывод
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml 2>&1 | tee compile.log
        
    - name: Check if build directory exists
      run: |
        echo "=== Checking build directory ==="
        ls -la .esphome/ 2>/dev/null || echo "No .esphome directory"
        find . -name "*.bin" -type f 2>/dev/null | head -10 || echo "No bin files found"
        
    - name: Upload compilation log
      uses: actions/upload-artifact@v4
      with:
        name: compilation-log
        path: compile.log
        retention-days: 1
