name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
    - run: find . -name "*.bin" -exec cp {} . \;
    - uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: "*.bin"
