name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile with Docker
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
        
    - name: List generated files
      run: |
        echo "=== Checking firmware files ==="
        find .esphome -name "*.bin" -type f | head -10
        
    - name: Upload ALL firmware files
      uses: actions/upload-artifact@v4
      with:
        name: ld2450-firmware
        path: .esphome/build/ld2450-radar/.pioenvs/ld2450-radar/*.bin
