name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile and prepare
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile lidar.yaml
        
    - name: Upload build folder
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: .esphome/build/
        retention-days: 1
