name: ESPHome Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Compile with Docker
      run: |
        docker run --rm -v $(pwd):/config esphome/esphome compile test.yaml
        
    - name: Copy firmware to root
      run: |
        cp .esphome/build/ld2450-radar/.pioenvs/ld2450-radar/firmware.ota.bin test-ota.bin
        cp .esphome/build/ld2450-radar/.pioenvs/ld2450-radar/firmware.factory.bin test-factory.bin
        cp .esphome/build/ld2450-radar/.pioenvs/ld2450-radar/firmware.bin test.bin
        
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: test-firmware
        path: |
          test-ota.bin
          test-factory.bin
          test-radar.bin
